### ISSUE TITLE
Execution Engine: Insert

### ISSUE THREAD

**Issue by Matthewar** [sperretta/HLP#23]
Child of #7 (Put general queries about execution engine there)
Branch: feature/execution-engine/insert

Add elements to an existing table. If table does not exist return error, otherwise return confirmation of successful write.

**Comment by Matthewar** [comment]
I've been using a special type ([see here](https://github.com/sperretta/HLP/blob/feature/parser/src/ReturnControl.Main.fs)) to deal with errors throughout the code. I would recommend using this, but as you've done with unit. IE Return either Result() or Error(<string goes here>). That way whatever error occurs can be returned to the user.

I need to consult @sperretta for the exact method of how exactly we're going to modify the "currentDatabase" argument of your code, since he's in charge of backend memory management.
The database modifying it done one level lower, and we'll have one module that can edit the database information.
Since this is a functional language, I think what we might do is call that lowest module from the execution engine, passing it the function that modifies the data. In that case your interface wouldn't change, except that the currentDatabase argument should be at the end I think?
The parser decrypts the tree - then would call something along the lines of
`memoryModule (insert tableName columnList valueList)`
The memory module would receive the bracketed information as a single argument, lets call it func, and then would run
`func internalDatabase`
and return the result of that query.

Data decrypted by the parser will know types, and can send those.
Do all the columns have to be in the list of just the ones you want to add data for?

**Comment by sighellan** [comment]
I have code that will add missing column names if not all are given (setting data as None), or infer all if the column names are left empty (empty list). But if they are left empty I assume that there is data for each column. In all cases I'm assuming that it's ordered.  

I'll move the database to the end then, and have a look at that error type.

**Comment by Matthewar** [comment]
Alright, that's great, cheers.
