### ISSUE TITLE
Execution Engine: Type Check

### ISSUE THREAD

**Issue by Matthewar** [sperretta/HLP#24]
Child of #7 (Put general queries about execution engine there)
Branch: feature/execution-engine/type-check

Takes variable name list, tables and the items to be compared, and checks if types match: further details to come.

**Comment by sighellan** [comment]
I have some code in the read-in section that makes sure all the rows have the same column types. Are you thinking of something like that?

**Comment by Matthewar** [comment]
It will involve that as one part of it yes: it type checks variables and values from the code with each other. If, for example, a variable is being compared against a column value in a "WHERE" statement, the types must match or an error occurs.

If you have something already to deal with some of these errors, it might be useful for whoever is assigned this task - if you could give the branch/file here, then whoever is assigned this task can take a look.

**Comment by sighellan** [comment]
dev/readTextFile/readingFile.fsx checkType as used in matchInputListsRec. I still need to change the error message output to something more useful. 

Ideally we would want something along the lines of a textbox/pop-up box in the GUI to alert the user, but that might be considered an enhancement?

**Comment by Matthewar** [comment]
So the way I believe it works is:
Enter query into textbox -> Hit send query button -> Data is authenticated by Simon's functions and sent to backend -> Backend processes and returns two things: list of variables and a list of tables OR returns an error -> Frontend displays results or error.

Error can simply be a textbox of some kind that spits out the string it's given.

**Comment by Matthewar** [comment]
Sections inside various execution engine modules should now do this.
Merged with execution engine paser.
