### ISSUE TITLE
Execution Engine: Delete

### ISSUE THREAD

**Issue by Matthewar** [sperretta/HLP#28]
Child of #7 (Put general queries about execution engine there)
Branch: feature/execution-engine/delete

Removes items (or an entire table) from the database. Returns status.

**Comment by sighellan** [comment]
`delete (tableList : string list) (testFunction : (Map<string,boxData> -> ReturnCode<bool>) option) : ReturnCode<database>`

@Matthewar  Confirming interface with parcer
