### ISSUE TITLE
Execution Engine: Create

### ISSUE THREAD

**Issue by Matthewar** [sperretta/HLP#29]
Child of #7 (Put general queries about execution engine there)
Branch: feature/execution-engine/create

Creates new table. Returns status.

**Comment by sighellan** [comment]
Looking at the [AST](https://github.com/sperretta/HLP/wiki/Abstract-Syntax-Tree-Format), it looks like the inputs should be the table name and a ColumnTypeList. Will this list include column names? If not, can we add another output of column names?

**Comment by Matthewar** [comment]
The ColumnTypeList is specified in the list section as a list of ColumnTypeItems (ovals are links to other parts of the diagram), which are shown at the very bottom of the page to be a column name and column type. This can be assembled in the execution engine parser into two separate lists or a list of some special type - what do you think is better?

**Comment by sighellan** [comment]
Just pick whatever is easier of separate lists, e.g. `[String None; Int None]`, `["Names"; "ID"]` or a list of tuples, e.g. `[("Names", String None);("ID", Int None)]` and I can work around it. The latter is the structure that will be saved in the database. Or if some other structure is easier just specify it for me. 

The interface will then be 
`create tableName columnTypeList database`
where columnTypeList is one or two lists, right?

**Comment by Matthewar** [comment]
I can save it into a list of tuples I believe, not too hard to move data around as the tree is unwrapped. Is that the easiest for you to use?

You are correct about the interface.
As an aside, is this type with String, Int, etc. in one of your files, and which one? When merging (don't worry for now because we have to sort a small amount of structure things first) we may have to move the type declaration to a separate file for use.

**Comment by sighellan** [comment]
I made a branch with it on, in its own module, [database structure](https://github.com/sperretta/HLP/blob/feature/databaseStructure/src/databaseStructure.fs). I want to have the types, and a small amount of general access functions in it.

**Comment by sighellan** [comment]
Tuples would be great.

**Comment by sighellan** [comment]
There's an initial implementation [here](https://github.com/sperretta/HLP/blob/feature/execution-engine/create/src/ExecutionEngineCreate.fs).
