### ISSUE TITLE
Build initial language specification

### ISSUE THREAD

**Issue by sperretta** [sperretta/HLP#4]
Write exhaustive list of language tokens and usage.

**Comment by sighellan** [comment]
Codeacademy has a list of commonly used commands - that might be a good place to start?
https://www.codecademy.com/articles/sql-commands?r=master

**Comment by Matthewar** [comment]
Do we prefer operators (+, -, *, /) or functions (add(x,y), sub(x,y), etc)

**Comment by sperretta** [comment]
Would ideally like to have both - if you look into converting between infix/postfix (reverse Polish) you should find a way to implement something very similar.

**Comment by Matthewar** [comment]
Alright, here is the inital language spec https://github.com/sperretta/HLP/wiki/Language-Spec

**Comment by sperretta** [comment]
The spec is not bad so far; it might help to make it a bit simpler however, as we would ideally like to start with a very basic subset of functionality (SELECT, INSERT, UPDATE, DELETE, etc.) and then build it up.

**Comment by Matthewar** [comment]
Updated into section for enhancements.

**Comment by Matthewar** [comment]
Now AST tree is completed, syntax can be mostly confirmed (allowing for minor changes).

Need review before close.

**Comment by sperretta** [comment]
I'm happy with the spec. If Sigrid agrees you can tag this as reviewed and close it.

**Comment by sighellan** [comment]
We need to resolve what data types we are using - this is different from the ones in DB structure.

**Comment by Matthewar** [comment]
This doesn't really mention types - what part are you referring to exactly?

**Comment by sighellan** [comment]
Value ::=

    <int> | <float> | <string> | varName

https://github.com/sperretta/HLP/wiki/Language-Spec

**Comment by Matthewar** [comment]
Alright updated that part

**Comment by sighellan** [comment]
Looks good.
