### ISSUE TITLE
Tokeniser

### ISSUE THREAD

**Issue by sperretta** [sperretta/HLP#5]
Module to take input stream and perform basic validation on tokens.

**Comment by sighellan** [comment]
It will also need to break down the input stream correctly into the different parts of the input.
Are we doing floats as well?

**Comment by sperretta** [comment]
Token type looks fine, could you maybe comment on the node aspect to make it clear?

**Comment by Matthewar** [comment]
Comment in the code or here?

I thought because we want the order to be maintained it should be a linked list - hence the node type wraps the different tokens with a link to the next node.

Alternatively I think I might be able to get the right order using a normal list and tail recursion.

**Comment by sperretta** [comment]
I think a normal list will be acceptable, there doesn't seem to be anything gained in using a linked list in this situation (you'd only ever really go for one if you need efficient adding/removing of elements within the list which doesn't apply in this case).

**Comment by Matthewar** [comment]
Sure, I'll make that change and continue with the tokeniser code itself.

**Comment by Matthewar** [comment]
May change numeric to allow int or float - currently storing in a float no matter what.

**Comment by Matthewar** [comment]
Added "CREATE TABLE" syntax that was missing, pretty essential component in order to have tables to use.

**Comment by Matthewar** [comment]
Code mostly completed: need tests and replacing "failwithf" with some error catching and reporting.

**Comment by Matthewar** [comment]
Merged to master - completed.
