### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by sperretta** [sperretta/HLP#6]
Module which takes tokeniser output and builds a parse tree (and performs syntax validation).

**Comment by Matthewar** [comment]
Currently progressing through drawing up the syntax tree, so the execution engine (#7) author will be able to easily implement their code. Have noted some possible changes to our build language spec (started in #4) that will make the execution engine task a bit more manageable.

* Considering removing allowing multiple "ORDER BY" columns
* Remove wrapped column name and simply use column name (IE no column functions / aliases in select)

These changes could be undone in enhancements

**Comment by Matthewar** [comment]
Most of the AST design is now mapped out.
[AST Format Here](https://github.com/sperretta/HLP/wiki/Abstract-Syntax-Tree-Format)

**Comment by Matthewar** [comment]
Merged and can now be closed.
