### ISSUE TITLE
Execution Engine

### ISSUE THREAD

**Issue by sperretta** [sperretta/HLP#7]
Validates parse tree, then executes contents:

* Contents are first evaluated with respect to the database.
* The query is executed.
* Results are returned to the user.

**Comment by Matthewar** [comment]
Rather than using variables, which could require complex memory allocation systems, we could have faux variables - a set number of free memory cells, similar to the set 16 registers in the VisUAL tool.

This wouldn't require a syntax change, but the execution engine could reject variable names different to a predetermined set.

**Comment by sperretta** [comment]
Good call, when work starts on the execution engine we can compare that to other systems, such as variable tables.

**Comment by sighellan** [comment]
We'll need to define what the output looks like. It should update the internal data structure, and then give some strings or other structure that the GUI can give to the user. 

For the variables, do you mean the names assigned by the users to different tables?

**Comment by Matthewar** [comment]
We need to have a discussion about whether we have a set number of variables (and then can monads/states to change them) with set names; alternatively we could have a list of variables as output.

I expect the output of the engine to be something along the lines of: (Obviously names are temporary and things in <> are to be filled in)
```{fsharp}
///Data stored in a variable
type varContent =
   | Integer of int
   | Float of float
   | Boolean of bool
   | Byte of byte
   | String of string

///A single variable
type variableType = (Name : string) * (Content : varContent)

///Output of results, alternatively could be a record
///<databaseListType> is already defined, a list of tables, tables are a list of rows, rows are a list of column data
///Tables would only contains the rows/columns of requested tables
type output =(Variables : variableType list) * (Tables : <databaseListType>)
```

**Comment by Matthewar** [comment]
I have separated the execution engine into a number of submodules. Submodules that access the database will do so with two functions "read" and "write". We need more details on database backend control to write these execution engine methods.
Submodules for this go under the branches feature/execution-engine/<submodule> (see submodules for chosen name).
All files in this group are in the namespace "ExecutionEngine"

**Comment by Matthewar** [comment]
Merged.
