### ISSUE TITLE
DB Structure

### ISSUE THREAD

**Issue by sperretta** [sperretta/HLP#8]
* Decide upon F# constructs and types with which to store data.
* Implement lock mechanism when accessing data.

**Comment by sighellan** [comment]
What datatype things are saved as doesn't really matter for the rest of the program as long as no accuracy is lost. But I'd assume strings were an easy place to start.

**Comment by Matthewar** [comment]
I believe SQL saves different types, we probably want _options_ too if we want to have blank cells.

Something like
```{f#}
let 'a DataNode = row : int * data : 'a opt * tail : 'a DataNode
let 'a DataHead = columnName : string * data : 'a DataNode * nextColumn : DataHead //Needs to know what data is in it perhaps, for saving/loading
```
Probably not syntactically correct at all, but I figured it's almost a linked list of linked lists?

**Comment by Matthewar** [comment]
The database structure looks good - except I don't think we need date or time as data types.

I think the structure of the database should be moved to its own module since it may need to be used in multiple places - probably should develop it in its own branch too - something like "feature/databaseStructure"

**Comment by sighellan** [comment]
Sure. I'll remove date and time and move it to its own module.

**Comment by sighellan** [comment]
I've moved it to its own module now. If people are OK with it we can merge it and then start using it in other modules. I've also updated the names used as they were getting rather confusing.
